### PR TITLE
Notes on inheriting from wagtail textract document

### PR DESCRIPTION
**Pull request by khink**
Factor out `transcription` field in Mixin model.

Document how to use wagtail_textract with an existing customized Document model.

Set `blank=True` to allow an empty transcription field when editing the Document (with modified `admin_form_fields` to also see `transcription`).

### CODE REVIEW

**Comment by khink** [comment]
@zerolab Is this something you could work with?

**Comment by zerolab** [comment]
Looks pretty good.

We were looking at this with @kaedroho and were wondering why not move the `save()` in the mixin.
It could use a few inline comments as to the order/reason it is doing it this way. Also, the convention is to use the mixin before the model. So moving the save in the mixin will have the desired effect.

Karl was also suggesting you can simplify the whole thing by calling `async_transcribe_document()` directly in `save()` and do away with the signals all together.

D

**Comment by khink** [comment]
@zerolab Thanks for these comments! See the last two commits. 

Do you feel this can be merged, or is something still missing?

**Comment by zerolab** [comment]
LGTM. @kaedroho is casting an eye as well.

**Comment by zerolab** [comment]
:shipit: 

Nice one!

**Comment by khink** [comment]
Thanks for the feedback!

**Pull request merged**
